services:

  main_app:
    build: .
    container_name: md-main_app
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: ["uvicorn", "--factory", "myasnaya_derevnya.main:create_app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - 8000:8000

  migrate:
    build: .
    command: ["alembic", "upgrade", "head"]
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  postgres:
    image: postgres:17-alpine
    container_name: md-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: