"""Initial migration

Revision ID: 0cc37b605109
Revises:
Create Date: 2026-10-03 15:09:52.593666+00:00

"""

from collections.abc import Sequence
from uuid import uuid7

import bcrypt
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc37b605109"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS organization")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("grants_all", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="auth",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("location_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="organization",
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["auth.roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_code"),
        schema="auth",
    )
    op.create_table(
        "user_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "identifier", name="uq_user_credentials_provider_identifier"
        ),
        sa.UniqueConstraint(
            "user_id", "provider", name="uq_user_credentials_user_provider"
        ),
        schema="auth",
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["auth.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["organization.locations.id"],
        ),
        sa.ForeignKeyConstraint(["role_id"], ["auth.roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        "ix_role_assignments_user_id",
        "user_roles",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        "ix_user_sessions_expires_at",
        "user_sessions",
        ["expires_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        "ix_user_sessions_user_id",
        "user_sessions",
        ["user_id"],
        unique=False,
        schema="auth",
    )

    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("grants_all", sa.Boolean()),
        schema="auth",
    )
    users_table = sa.table(
        "users",
        sa.column("id", sa.UUID()),
        sa.column("status", sa.String()),
        schema="auth",
    )
    credentials_table = sa.table(
        "user_credentials",
        sa.column("id", sa.UUID()),
        sa.column("user_id", sa.UUID()),
        sa.column("provider", sa.String()),
        sa.column("identifier", sa.String()),
        sa.column("password_hash", sa.String()),
        schema="auth",
    )
    user_roles_table = sa.table(
        "user_roles",
        sa.column("id", sa.UUID()),
        sa.column("user_id", sa.UUID()),
        sa.column("role_id", sa.UUID()),
        sa.column("created_by", sa.UUID()),
        schema="auth",
    )

    # 2. Генерируем UUID для связей во время выполнения миграции
    admin_user_id = uuid7()
    admin_role_id = uuid7()

    password_bytes = b"admin"
    salt = bcrypt.gensalt(rounds=12)  # Ровно 12 раундов, как в твоем сервисе
    local_bcrypt_hash = bcrypt.hashpw(password_bytes, salt).decode("utf-8")

    # 3. Накатываем данные одной атомарной пачкой
    op.bulk_insert(
        roles_table,
        [
            {
                "id": admin_role_id,
                "code": "super_admin",
                "name": "Системный администратор",
                "grants_all": True,
            }
        ],
    )

    op.bulk_insert(users_table, [{"id": admin_user_id, "status": "active"}])

    op.bulk_insert(
        credentials_table,
        [
            {
                "id": uuid7(),
                "user_id": admin_user_id,
                "provider": "password",
                "identifier": "admin",
                # SHA-256 хэш от пароля "admin"
                "password_hash": local_bcrypt_hash,
            }
        ],
    )

    op.bulk_insert(
        user_roles_table,
        [
            {
                "id": uuid7(),
                "user_id": admin_user_id,
                "role_id": admin_role_id,
                "created_by": admin_user_id,
            }
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions", schema="auth")
    op.drop_index(
        "ix_user_sessions_expires_at", table_name="user_sessions", schema="auth"
    )
    op.drop_table("user_sessions", schema="auth")
    op.drop_index("ix_role_assignments_user_id", table_name="user_roles", schema="auth")
    op.drop_table("user_roles", schema="auth")
    op.drop_table("user_credentials", schema="auth")
    op.drop_table("role_permissions", schema="auth")
    op.drop_table("locations", schema="organization")
    op.drop_table("users", schema="auth")
    op.drop_table("roles", schema="auth")
    # ### end Alembic commands ###
