"""initial

Revision ID: dece99745ba4
Revises:
Create Date: 2026-10-10 00:58:49.333654+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dece99745ba4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS business")
    op.execute("CREATE SCHEMA IF NOT EXISTS catalog")
    op.execute("CREATE SCHEMA IF NOT EXISTS staff")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema="auth",
    )
    op.create_table(
        "org_units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=512), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["business.org_units.id"],
            name=op.f("fk_org_units_parent_id_org_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_units")),
        sa.UniqueConstraint("code", name="uq_org_units_code"),
        schema="business",
    )
    op.create_index(
        "ix_org_units_parent_id",
        "org_units",
        ["parent_id"],
        unique=False,
        schema="business",
    )
    op.create_index(
        "ix_org_units_type", "org_units", ["type"], unique=False, schema="business"
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["catalog.categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        schema="catalog",
    )
    op.create_index(
        "ix_categories_parent_id",
        "categories",
        ["parent_id"],
        unique=False,
        schema="catalog",
    )
    op.create_table(
        "price_lists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_lists")),
        sa.UniqueConstraint("name", name=op.f("uq_price_lists_name")),
        schema="catalog",
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=False),
        sa.Column("hired_at", sa.Date(), nullable=False),
        sa.Column("dismissed_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        schema="staff",
    )
    op.create_index(
        "ix_employees_last_name",
        "employees",
        ["last_name"],
        unique=False,
        schema="staff",
    )
    op.create_index(
        "uq_employees_user_id", "employees", ["user_id"], unique=True, schema="staff"
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("level", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_assignable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_wildcard", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
        schema="staff",
    )
    op.create_table(
        "user_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credential_type", sa.String(length=30), nullable=False),
        sa.Column("secret", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_credentials")),
        sa.UniqueConstraint(
            "user_id",
            "credential_type",
            name="uq_user_credentials_user_credential_type",
        ),
        schema="auth",
    )
    op.create_index(
        "ix_user_credentials_user_id",
        "user_credentials",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("identity_type", sa.String(length=50), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint(
            "identity_type", "identifier", name="uq_user_identities_provider_identifier"
        ),
        schema="auth",
    )
    op.create_index(
        "ix_user_identities_user_id",
        "user_identities",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        schema="auth",
    )
    op.create_index(
        "ix_user_sessions_expires_at",
        "user_sessions",
        ["expires_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        "ix_user_sessions_user_id",
        "user_sessions",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_unit_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("kpp", sa.String(length=9), nullable=False),
        sa.Column("ogrn", sa.String(length=15), nullable=False),
        sa.Column("legal_address", sa.String(length=512), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"],
            ["business.org_units.id"],
            name=op.f("fk_companies_org_unit_id_org_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("code", name=op.f("uq_companies_code")),
        sa.UniqueConstraint("org_unit_id", name=op.f("uq_companies_org_unit_id")),
        schema="business",
    )
    op.create_table(
        "org_unit_closure",
        sa.Column("ancestor_id", sa.UUID(), nullable=False),
        sa.Column("descendant_id", sa.UUID(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ancestor_id"],
            ["business.org_units.id"],
            name=op.f("fk_org_unit_closure_ancestor_id_org_units"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["descendant_id"],
            ["business.org_units.id"],
            name=op.f("fk_org_unit_closure_descendant_id_org_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "ancestor_id", "descendant_id", name=op.f("pk_org_unit_closure")
        ),
        schema="business",
    )
    op.create_index(
        "ix_org_unit_closure_descendant",
        "org_unit_closure",
        ["descendant_id"],
        unique=False,
        schema="business",
    )
    op.create_table(
        "nomenclatures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("gtin", sa.String(length=14), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["catalog.categories.id"],
            name=op.f("fk_nomenclatures_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nomenclatures")),
        sa.UniqueConstraint("sku", name=op.f("uq_nomenclatures_sku")),
        schema="catalog",
    )
    op.create_index(
        "ix_nomenclatures_category_id",
        "nomenclatures",
        ["category_id"],
        unique=False,
        schema="catalog",
    )
    op.create_index(
        "ix_nomenclatures_type",
        "nomenclatures",
        ["type"],
        unique=False,
        schema="catalog",
    )
    op.create_table(
        "role_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("org_unit_id", sa.UUID(), nullable=True),
        sa.Column(
            "include_descendants", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["staff.roles.id"],
            name=op.f("fk_role_assignments_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
        schema="staff",
    )
    op.create_index(
        "ix_role_assignments_org_unit",
        "role_assignments",
        ["org_unit_id"],
        unique=False,
        schema="staff",
    )
    op.create_index(
        "ix_role_assignments_user_active",
        "role_assignments",
        ["user_id", "status"],
        unique=False,
        schema="staff",
    )
    op.create_index(
        "uq_role_assignments_active_global",
        "role_assignments",
        ["user_id", "role_id"],
        unique=True,
        schema="staff",
        postgresql_where=sa.text("status = 'active' AND org_unit_id IS NULL"),
    )
    op.create_index(
        "uq_role_assignments_active_scoped",
        "role_assignments",
        ["user_id", "role_id", "org_unit_id"],
        unique=True,
        schema="staff",
        postgresql_where=sa.text("status = 'active' AND org_unit_id IS NOT NULL"),
    )
    op.create_table(
        "role_grant_rules",
        sa.Column("granter_role_id", sa.UUID(), nullable=False),
        sa.Column("grantable_role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grantable_role_id"],
            ["staff.roles.id"],
            name=op.f("fk_role_grant_rules_grantable_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["granter_role_id"],
            ["staff.roles.id"],
            name=op.f("fk_role_grant_rules_granter_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "granter_role_id", "grantable_role_id", name=op.f("pk_role_grant_rules")
        ),
        schema="staff",
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["staff.roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "role_id", "permission_code", name=op.f("pk_role_permissions")
        ),
        schema="staff",
    )
    op.create_table(
        "prices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nomenclature_id", sa.UUID(), nullable=False),
        sa.Column("price_list_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("value >= 0", name=op.f("ck_prices_value_non_negative")),
        sa.ForeignKeyConstraint(
            ["nomenclature_id"],
            ["catalog.nomenclatures.id"],
            name=op.f("fk_prices_nomenclature_id_nomenclatures"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["price_list_id"],
            ["catalog.price_lists.id"],
            name=op.f("fk_prices_price_list_id_price_lists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prices")),
        sa.UniqueConstraint(
            "nomenclature_id", "price_list_id", name="uq_prices_nomenclature_price_list"
        ),
        schema="catalog",
    )
    op.create_index(
        "ix_prices_nomenclature_id",
        "prices",
        ["nomenclature_id"],
        unique=False,
        schema="catalog",
    )
    op.create_index(
        "ix_prices_price_list_id",
        "prices",
        ["price_list_id"],
        unique=False,
        schema="catalog",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prices_price_list_id", table_name="prices", schema="catalog")
    op.drop_index("ix_prices_nomenclature_id", table_name="prices", schema="catalog")
    op.drop_table("prices", schema="catalog")
    op.drop_table("role_permissions", schema="staff")
    op.drop_table("role_grant_rules", schema="staff")
    op.drop_index(
        "uq_role_assignments_active_scoped",
        table_name="role_assignments",
        schema="staff",
        postgresql_where=sa.text("status = 'active' AND org_unit_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_role_assignments_active_global",
        table_name="role_assignments",
        schema="staff",
        postgresql_where=sa.text("status = 'active' AND org_unit_id IS NULL"),
    )
    op.drop_index(
        "ix_role_assignments_user_active", table_name="role_assignments", schema="staff"
    )
    op.drop_index(
        "ix_role_assignments_org_unit", table_name="role_assignments", schema="staff"
    )
    op.drop_table("role_assignments", schema="staff")
    op.drop_index("ix_nomenclatures_type", table_name="nomenclatures", schema="catalog")
    op.drop_index(
        "ix_nomenclatures_category_id", table_name="nomenclatures", schema="catalog"
    )
    op.drop_table("nomenclatures", schema="catalog")
    op.drop_index(
        "ix_org_unit_closure_descendant",
        table_name="org_unit_closure",
        schema="business",
    )
    op.drop_table("org_unit_closure", schema="business")
    op.drop_table("companies", schema="business")
    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions", schema="auth")
    op.drop_index(
        "ix_user_sessions_expires_at", table_name="user_sessions", schema="auth"
    )
    op.drop_table("user_sessions", schema="auth")
    op.drop_index(
        "ix_user_identities_user_id", table_name="user_identities", schema="auth"
    )
    op.drop_table("user_identities", schema="auth")
    op.drop_index(
        "ix_user_credentials_user_id", table_name="user_credentials", schema="auth"
    )
    op.drop_table("user_credentials", schema="auth")
    op.drop_table("roles", schema="staff")
    op.drop_index("uq_employees_user_id", table_name="employees", schema="staff")
    op.drop_index("ix_employees_last_name", table_name="employees", schema="staff")
    op.drop_table("employees", schema="staff")
    op.drop_table("price_lists", schema="catalog")
    op.drop_index("ix_categories_parent_id", table_name="categories", schema="catalog")
    op.drop_table("categories", schema="catalog")
    op.drop_index("ix_org_units_type", table_name="org_units", schema="business")
    op.drop_index("ix_org_units_parent_id", table_name="org_units", schema="business")
    op.drop_table("org_units", schema="business")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
