"""inventory module

Revision ID: 10e395367fc2
Revises: dece99745ba4
Create Date: 2026-10-10 16:04:57.597334+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10e395367fc2"
down_revision: str | Sequence[str] | None = "dece99745ba4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS inventory")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_lots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nomenclature_id", sa.UUID(), nullable=False),
        sa.Column("lot_code", sa.String(length=64), nullable=False),
        sa.Column("produced_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("supplier_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_lots")),
        sa.UniqueConstraint(
            "nomenclature_id", "lot_code", name="uq_stock_lots_nomenclature_lot_code"
        ),
        schema="inventory",
    )
    op.create_index(
        "ix_stock_lots_expires_at",
        "stock_lots",
        ["expires_at"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "warehouses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_unit_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("code", name="uq_warehouses_code"),
        schema="inventory",
    )
    op.create_index(
        "ix_warehouses_org_unit_id",
        "warehouses",
        ["org_unit_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("supplier_name", sa.String(length=255), nullable=True),
        sa.Column("supplier_document_number", sa.String(length=64), nullable=True),
        sa.Column("comment", sa.String(length=512), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["inventory.warehouses.id"],
            name=op.f("fk_receipts_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        schema="inventory",
    )
    op.create_index(
        "ix_receipts_status", "receipts", ["status"], unique=False, schema="inventory"
    )
    op.create_index(
        "ix_receipts_warehouse_occurred_at",
        "receipts",
        ["warehouse_id", "occurred_at"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "stock_balances",
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("nomenclature_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "average_unit_cost",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("total_value", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_stock_balances_quantity_non_negative")
        ),
        sa.CheckConstraint(
            "total_value >= 0", name=op.f("ck_stock_balances_total_value_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["inventory.warehouses.id"],
            name=op.f("fk_stock_balances_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "warehouse_id", "nomenclature_id", name=op.f("pk_stock_balances")
        ),
        schema="inventory",
    )
    op.create_table(
        "stock_lot_balances",
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("nomenclature_id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_stock_lot_balances_quantity_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["inventory.stock_lots.id"],
            name=op.f("fk_stock_lot_balances_lot_id_stock_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["inventory.warehouses.id"],
            name=op.f("fk_stock_lot_balances_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "warehouse_id",
            "nomenclature_id",
            "lot_id",
            name=op.f("pk_stock_lot_balances"),
        ),
        schema="inventory",
    )
    op.create_index(
        "ix_stock_lot_balances_lot_id",
        "stock_lot_balances",
        ["lot_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "stock_postings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column(
            "posted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("posted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["inventory.warehouses.id"],
            name=op.f("fk_stock_postings_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_postings")),
        sa.UniqueConstraint(
            "document_type", "document_id", name="uq_stock_postings_document"
        ),
        schema="inventory",
    )
    op.create_index(
        "ix_stock_postings_warehouse_posted_at",
        "stock_postings",
        ["warehouse_id", "posted_at"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "write_offs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("comment", sa.String(length=512), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["inventory.warehouses.id"],
            name=op.f("fk_write_offs_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_write_offs")),
        schema="inventory",
    )
    op.create_index(
        "ix_write_offs_status",
        "write_offs",
        ["status"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        "ix_write_offs_warehouse_occurred_at",
        "write_offs",
        ["warehouse_id", "occurred_at"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "receipt_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("nomenclature_id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=True),
        sa.Column("lot_code", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "unit_cost",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("total_cost", sa.BigInteger(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_receipt_lines_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["inventory.stock_lots.id"],
            name=op.f("fk_receipt_lines_lot_id_stock_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["inventory.receipts.id"],
            name=op.f("fk_receipt_lines_receipt_id_receipts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_lines")),
        schema="inventory",
    )
    op.create_index(
        "ix_receipt_lines_receipt_id",
        "receipt_lines",
        ["receipt_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("nomenclature_id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=True),
        sa.Column("movement_type", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("total_cost", sa.BigInteger(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(quantity > 0 AND total_cost >= 0) OR (quantity < 0 AND total_cost <= 0)",
            name=op.f("ck_stock_movements_sign_consistent"),
        ),
        sa.CheckConstraint(
            "quantity <> 0", name=op.f("ck_stock_movements_quantity_non_zero")
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["inventory.stock_lots.id"],
            name=op.f("fk_stock_movements_lot_id_stock_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["inventory.stock_postings.id"],
            name=op.f("fk_stock_movements_posting_id_stock_postings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["inventory.warehouses.id"],
            name=op.f("fk_stock_movements_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
        schema="inventory",
    )
    op.create_index(
        "ix_stock_movements_lot_id",
        "stock_movements",
        ["lot_id"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        "ix_stock_movements_posting_id",
        "stock_movements",
        ["posting_id"],
        unique=False,
        schema="inventory",
    )
    op.create_index(
        "ix_stock_movements_warehouse_nomenclature",
        "stock_movements",
        ["warehouse_id", "nomenclature_id", "occurred_at"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "write_off_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("write_off_id", sa.UUID(), nullable=False),
        sa.Column("nomenclature_id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=True),
        sa.Column("lot_code", sa.String(length=64), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_write_off_lines_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["inventory.stock_lots.id"],
            name=op.f("fk_write_off_lines_lot_id_stock_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["write_off_id"],
            ["inventory.write_offs.id"],
            name=op.f("fk_write_off_lines_write_off_id_write_offs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_write_off_lines")),
        schema="inventory",
    )
    op.create_index(
        "ix_write_off_lines_write_off_id",
        "write_off_lines",
        ["write_off_id"],
        unique=False,
        schema="inventory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_write_off_lines_write_off_id",
        table_name="write_off_lines",
        schema="inventory",
    )
    op.drop_table("write_off_lines", schema="inventory")
    op.drop_index(
        "ix_stock_movements_warehouse_nomenclature",
        table_name="stock_movements",
        schema="inventory",
    )
    op.drop_index(
        "ix_stock_movements_posting_id",
        table_name="stock_movements",
        schema="inventory",
    )
    op.drop_index(
        "ix_stock_movements_lot_id", table_name="stock_movements", schema="inventory"
    )
    op.drop_table("stock_movements", schema="inventory")
    op.drop_index(
        "ix_receipt_lines_receipt_id", table_name="receipt_lines", schema="inventory"
    )
    op.drop_table("receipt_lines", schema="inventory")
    op.drop_index(
        "ix_write_offs_warehouse_occurred_at",
        table_name="write_offs",
        schema="inventory",
    )
    op.drop_index("ix_write_offs_status", table_name="write_offs", schema="inventory")
    op.drop_table("write_offs", schema="inventory")
    op.drop_index(
        "ix_stock_postings_warehouse_posted_at",
        table_name="stock_postings",
        schema="inventory",
    )
    op.drop_table("stock_postings", schema="inventory")
    op.drop_index(
        "ix_stock_lot_balances_lot_id",
        table_name="stock_lot_balances",
        schema="inventory",
    )
    op.drop_table("stock_lot_balances", schema="inventory")
    op.drop_table("stock_balances", schema="inventory")
    op.drop_index(
        "ix_receipts_warehouse_occurred_at", table_name="receipts", schema="inventory"
    )
    op.drop_index("ix_receipts_status", table_name="receipts", schema="inventory")
    op.drop_table("receipts", schema="inventory")
    op.drop_index(
        "ix_warehouses_org_unit_id", table_name="warehouses", schema="inventory"
    )
    op.drop_table("warehouses", schema="inventory")
    op.drop_index(
        "ix_stock_lots_expires_at", table_name="stock_lots", schema="inventory"
    )
    op.drop_table("stock_lots", schema="inventory")
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS inventory")
