"""initial

Revision ID: ba055ac15fff
Revises:
Create Date: 2026-10-04 16:18:17.565529+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba055ac15fff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("grants_all", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="staff",
    )
    op.create_table(
        "user_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credential_type", sa.String(length=30), nullable=False),
        sa.Column("secret", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "credential_type",
            name="uq_user_credentials_user_credential_type",
        ),
        schema="auth",
    )
    op.create_index(
        "ix_user_credentials_user_id",
        "user_credentials",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("identity_type", sa.String(length=50), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "identity_type", "identifier", name="uq_user_identities_provider_identifier"
        ),
        schema="auth",
    )
    op.create_index(
        "ix_user_identities_user_id",
        "user_identities",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        "ix_user_sessions_expires_at",
        "user_sessions",
        ["expires_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        "ix_user_sessions_user_id",
        "user_sessions",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=False),
        sa.Column("hired_at", sa.Date(), nullable=False),
        sa.Column("dismissed_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="staff",
    )
    op.create_index(
        "ix_employees_last_name",
        "employees",
        ["last_name"],
        unique=False,
        schema="staff",
    )
    op.create_index(
        "uq_employees_user_id",
        "employees",
        ["user_id"],
        unique=True,
        schema="staff",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["staff.roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_code"),
        schema="staff",
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["auth.users.id"],
        ),
        sa.ForeignKeyConstraint(["role_id"], ["staff.roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="staff",
    )
    op.create_index(
        "ix_role_assignments_user_id",
        "user_roles",
        ["user_id"],
        unique=False,
        schema="staff",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_role_assignments_user_id", table_name="user_roles", schema="staff"
    )
    op.drop_table("user_roles", schema="staff")
    op.drop_table("role_permissions", schema="staff")
    op.drop_index(
        "uq_employees_user_id",
        table_name="employees",
        schema="staff",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index("ix_employees_last_name", table_name="employees", schema="staff")
    op.drop_table("employees", schema="staff")
    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions", schema="auth")
    op.drop_index(
        "ix_user_sessions_expires_at", table_name="user_sessions", schema="auth"
    )
    op.drop_table("user_sessions", schema="auth")
    op.drop_index(
        "ix_user_identities_user_id", table_name="user_identities", schema="auth"
    )
    op.drop_table("user_identities", schema="auth")
    op.drop_index(
        "ix_user_credentials_user_id", table_name="user_credentials", schema="auth"
    )
    op.drop_table("user_credentials", schema="auth")
    op.drop_table("roles", schema="staff")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
