"""initial

Revision ID: 8561e16cee29
Revises:
Create Date: 2026-10-06 00:11:29.344214+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8561e16cee29"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS business")
    op.execute("CREATE SCHEMA IF NOT EXISTS staff")
    op.execute("CREATE SCHEMA IF NOT EXISTS inventory")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="business",
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("level", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_assignable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_wildcard", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="staff",
    )
    op.create_table(
        "user_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credential_type", sa.String(length=30), nullable=False),
        sa.Column("secret", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "credential_type",
            name="uq_user_credentials_user_credential_type",
        ),
        schema="auth",
    )
    op.create_index(
        "ix_user_credentials_user_id",
        "user_credentials",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("identity_type", sa.String(length=50), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "identity_type", "identifier", name="uq_user_identities_provider_identifier"
        ),
        schema="auth",
    )
    op.create_index(
        "ix_user_identities_user_id",
        "user_identities",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        "ix_user_sessions_expires_at",
        "user_sessions",
        ["expires_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        "ix_user_sessions_user_id",
        "user_sessions",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "org_units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=512), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "type IN ('production','cafe_group','cafe','shop_group','shop','department')",
            name="ck_org_units_type",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["business.companies.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["business.org_units.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "code", name="uq_org_units_company_code"),
        schema="business",
    )
    op.create_index(
        "ix_org_units_company_id",
        "org_units",
        ["company_id"],
        unique=False,
        schema="business",
    )
    op.create_index(
        "ix_org_units_parent_id",
        "org_units",
        ["parent_id"],
        unique=False,
        schema="business",
    )
    op.create_index(
        "ix_org_units_type",
        "org_units",
        ["company_id", "type"],
        unique=False,
        schema="business",
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=False),
        sa.Column("hired_at", sa.Date(), nullable=False),
        sa.Column("dismissed_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="staff",
    )
    op.create_index(
        "ix_employees_last_name",
        "employees",
        ["last_name"],
        unique=False,
        schema="staff",
    )
    op.create_index(
        "uq_employees_user_id", "employees", ["user_id"], unique=True, schema="staff"
    )
    op.create_table(
        "role_grant_rules",
        sa.Column("granter_role_id", sa.UUID(), nullable=False),
        sa.Column("grantable_role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grantable_role_id"], ["staff.roles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["granter_role_id"], ["staff.roles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("granter_role_id", "grantable_role_id"),
        schema="staff",
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["staff.roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_code"),
        schema="staff",
    )
    op.create_table(
        "org_unit_closure",
        sa.Column("ancestor_id", sa.UUID(), nullable=False),
        sa.Column("descendant_id", sa.UUID(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ancestor_id"], ["business.org_units.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["descendant_id"], ["business.org_units.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ancestor_id", "descendant_id"),
        schema="business",
    )
    op.create_index(
        "ix_org_unit_closure_descendant",
        "org_unit_closure",
        ["descendant_id"],
        unique=False,
        schema="business",
    )
    op.create_table(
        "warehouses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_unit_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_unit_id"], ["business.org_units.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_unit_id", "code", name="uq_warehouses_org_unit_code"),
        schema="inventory",
    )
    op.create_index(
        "ix_warehouses_org_unit_id",
        "warehouses",
        ["org_unit_id"],
        unique=False,
        schema="inventory",
    )
    op.create_table(
        "role_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("org_unit_id", sa.UUID(), nullable=True),
        sa.Column(
            "include_descendants", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("granted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active','revoked')", name="ck_role_assignments_status"
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["business.companies.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"], ["auth.users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["org_unit_id"], ["business.org_units.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["staff.roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="staff",
    )
    op.create_index(
        "ix_role_assignments_org_unit",
        "role_assignments",
        ["org_unit_id"],
        unique=False,
        schema="staff",
    )
    op.create_index(
        "ix_role_assignments_user_active",
        "role_assignments",
        ["user_id", "company_id", "status"],
        unique=False,
        schema="staff",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_role_assignments_user_active", table_name="role_assignments", schema="staff"
    )
    op.drop_index(
        "ix_role_assignments_org_unit", table_name="role_assignments", schema="staff"
    )
    op.drop_table("role_assignments", schema="staff")
    op.drop_index(
        "ix_warehouses_org_unit_id", table_name="warehouses", schema="inventory"
    )
    op.drop_table("warehouses", schema="inventory")
    op.drop_index(
        "ix_org_unit_closure_descendant",
        table_name="org_unit_closure",
        schema="business",
    )
    op.drop_table("org_unit_closure", schema="business")
    op.drop_table("role_permissions", schema="staff")
    op.drop_table("role_grant_rules", schema="staff")
    op.drop_index("uq_employees_user_id", table_name="employees", schema="staff")
    op.drop_index("ix_employees_last_name", table_name="employees", schema="staff")
    op.drop_table("employees", schema="staff")
    op.drop_index("ix_org_units_type", table_name="org_units", schema="business")
    op.drop_index("ix_org_units_parent_id", table_name="org_units", schema="business")
    op.drop_index("ix_org_units_company_id", table_name="org_units", schema="business")
    op.drop_table("org_units", schema="business")
    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions", schema="auth")
    op.drop_index(
        "ix_user_sessions_expires_at", table_name="user_sessions", schema="auth"
    )
    op.drop_table("user_sessions", schema="auth")
    op.drop_index(
        "ix_user_identities_user_id", table_name="user_identities", schema="auth"
    )
    op.drop_table("user_identities", schema="auth")
    op.drop_index(
        "ix_user_credentials_user_id", table_name="user_credentials", schema="auth"
    )
    op.drop_table("user_credentials", schema="auth")
    op.drop_table("roles", schema="staff")
    op.drop_table("companies", schema="business")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
